
include:
  - board: akdk_bt1
    shield: 43wireless1
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artificial-name: 43WIRELESS1
  - board: akdk_bt1
    shield: settings_reset
    artificial-name: settings_reset-akdk_bt1-zmk
